name =input("Enter full name: ")
idnum =input("Enter ID Number:")
course =input("Enter Course:")
section =input("Enter Section:")
a1 = eval(input("Enter 1st Quarter Grade:"))
a2 = eval(input("Enter 2nd Quarter Grade:"))
a3 = eval(input("Enter 3rd Quarter Grade:"))
a4 = eval(input("Enter 4th Quarter Grade:"))
avg = (a1 + a2 + a3 + a4)/4
print("Your details are")
print("Full name is "+ name)
print("ID Number is "+ idnum)
print("Course is "+ course)
print("Section is "+ section)
print("Average is: " + str(avg))
